# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_Main_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1098, 696)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(80, 20, 881, 581))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(50, 10, 711, 151))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.start_Button = QtWidgets.QPushButton(self.tab)
        self.start_Button.setGeometry(QtCore.QRect(210, 240, 411, 41))
        self.start_Button.setObjectName("start_Button")
        self.settings_Button = QtWidgets.QPushButton(self.tab)
        self.settings_Button.setGeometry(QtCore.QRect(210, 300, 411, 41))
        self.settings_Button.setObjectName("settings_Button")
        self.closeButton = QtWidgets.QPushButton(self.tab)
        self.closeButton.setGeometry(QtCore.QRect(100, 460, 621, 41))
        self.closeButton.setObjectName("closeButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.drawField_2 = QtWidgets.QLabel(self.tab_2)
        self.drawField_2.setGeometry(QtCore.QRect(330, 180, 561, 241))
        self.drawField_2.setAutoFillBackground(False)
        self.drawField_2.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.drawField_2.setText("")
        self.drawField_2.setObjectName("drawField_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1098, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.closeButton.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

#Тут надо разобраться с тем как применять изменения в коде на виджет(решил)
        self.tabWidget.tabBar().hide()
        self.tabWidget.setCurrentIndex(0)#Тут запуск таба который будет первый при запуске приложения


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ZumaGame"))
        self.label.setText(_translate("MainWindow", "Добро пожаловать в мою игру"))
        self.start_Button.setText(_translate("MainWindow", "Начать игру"))
        self.settings_Button.setText(_translate("MainWindow", "Настройки"))
        self.closeButton.setText(_translate("MainWindow", "Закрыть"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Главное меню"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Игра"))
        self.menu.setTitle(_translate("MainWindow", "Настройки"))
